name: windows
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    name: windows build
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Install Rustup using win.rustup.rs
      run: |
        # Disable the download progress bar which can cause perf issues
        $ProgressPreference = "SilentlyContinue"
        Invoke-WebRequest https://win.rustup.rs/ -OutFile rustup-init.exe
        .\rustup-init.exe -y --default-host=x86_64-pc-windows-msvc --default-toolchain=none
        del rustup-init.exe
        rustup target add x86_64-pc-windows-msvc
      shell: powershell
    - name: Build
      shell: cmd
      run: cargo build --release
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: photos_sorter.exe
        path: target/release/photos_sorter.exe
    
